name: Setup Environment
description: Sets up environment
runs:
  using: "composite"
  steps:
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.28.0'