name: Build and Test

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  #  lint:
  #    runs-on: ubuntu-latest
  #    permissions:
  #      # Give the default GITHUB_TOKEN write permission to commit and push the
  #      # added or changed files to the repository.
  #      contents: write
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v4
  #
  #      - name: Set up Clang
  #        uses: egor-tensin/setup-clang@v1
  #
  #      - name: Install CMake
  #        uses: jwlawson/actions-setup-cmake@v2
  #        with:
  #          cmake-version: '3.28.0'
  #
  #      - name: Create build directory
  #        run: mkdir build
  #        working-directory: ${{ github.workspace }}
  #
  #      - name: Install clang-tidy
  #        run: |
  #          sudo apt-get update
  #          sudo apt-get install -y clang-tidy clang-format
  #
  #      - name: Prepare compile_commands.json
  #        run: |
  #          cmake -B build \
  #          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  #          -DCMAKE_C_COMPILER=$(which clang) \
  #          -DCMAKE_CXX_COMPILER=$(which clang++) \
  #          -DCMAKE_BUILD_TYPE=Release \
  #      - name: Run clang-tidy
  #        run: ./tools/lint.sh
  #      - name: Run clang-format
  #        run: ./tools/format.sh
  #
  #      - name: Commit changes
  #        uses: stefanzweifel/git-auto-commit-action@v5
  #        with:
  #          commit_message: "chore(💅): Prettify"
  #          branch: ${{ github.head_ref }}

  build:
    runs-on: ubuntu-latest
    #    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.28.0'

      - name: Install build-essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential mesa-common-dev libegl1-mesa-dev mesa-utils libasound2-dev libxext-dev

      - name: Create build directory
        run: mkdir build
        working-directory: ${{ github.workspace }}

      - name: Configure CMake
        shell: bash
        run: |
          cmake ${{ github.workspace }} \
          -DCMAKE_C_COMPILER=$(which clang) \
          -DCMAKE_CXX_COMPILER=$(which clang++) \
          -DCMAKE_BUILD_TYPE=Release \
          -B ${{ github.workspace }}/build/Release
        working-directory: ${{ github.workspace }}/build

      - name: log
        shell: bash
        run: ls -la

      - name: Build
        run: make VERBOSE=1
        working-directory: ${{ github.workspace }}/build/Release

      - uses: actions/upload-artifact@v4
        with:
          name: game_linux
          path: ${{ github.workspace }}/bin
